# Use an official Node.js runtime as a parent image
FROM node:20

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code into the container
COPY . .

# Command to run your index.js file
CMD ["node", "src/Bots/Bot1/index.js"]
