# Use node version 21
FROM node:21

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code into the container
COPY . .

# Command to run both bots at once
CMD ["npm", "run", "all"]

# docker build -f DockerFile -t test .