name: Node.js Discord Bot

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install  # Installs all dependencies listed in package.json
      
    - name: Increase PushCounter
      run: node Hooks/Functions/Increase-push.js


    - name: Status
      run: git status

    - name: Commit Payload 
      run: |
        git config --global user.email "SimonTristanDev@gmail.com" 
        git config --global user.name "GitHub Actions Bot" 
        git add Hooks/payload.json
        git commit -m "Update" || echo "nothing to commit"
        git push origin main

    - name: Push Changes
      env: 
        GitHub-TOKEN: ${{ secrets.GITHUB_TOKEN }}

      run: |
        git push origin main || echo "nothing to push"

