name: Commit-Test[1]

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Test
      run: node Hooks/GitHub.js
