name: Commit

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List files (for debugging)
      run: ls -R

    - name: Test
      run: node Hooks/GitHub.js
