name: Node.js Discord Bot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated to v3
      with:
        node-version: '20'  # Specify Node.js version

    - name: Install dependencies
      run: npm install 

    - name: Start Bot1 
      env: 
        TokenForChatBot: ${{ secrets.TOKEN }}  # Access the token
      run: npm run Bot1
